package:
    name: basta
    version: 1.3

source:
    git_rev: "1.3.1"
    git_url: https://github.com/timkahlke/BASTA.git


build:
    script: python setup.py install --single-version-externally-managed --record record.txt 
    number: 1
    noarch: generic

requirements:
    build:
        - python 2.7
        - setuptools
    run:
        - python 2.7
        - leveldb
        - plyvel
        - krona
        - wget

test:
    imports:
        - plyvel
        - basta
        
    commands:
        - python -m unittest discover -s basta        

about:
    home: https://github.com/timkahlke/BASTA
    license: GPL3
    license_file: LICENSE
    


