package:
    name: basta
    version: 1.4

source:
    git_rev: "1.4.0"
    git_url: https://github.com/timkahlke/BASTA.git


build:
    script: python setup.py install --egg
    number: 0
    noarch: python

requirements:
    build:
        - python 3
        - setuptools
    run:
        - python 3
        - leveldb
        - plyvel
        - krona
        - wget

test:
    imports:
        - plyvel
        - basta
        
    commands:
        - python -m unittest discover -s basta        

about:
    home: https://github.com/timkahlke/BASTA
    license: GPL3
    license_file: LICENSE
    


